### ISSUE TITLE
"mouseOver" & "mouseLeft" on android but no pinch to scale?

### ISSUE THREAD

**Issue by TobiasIsak** [graphstream/gs-ui-android#17]
Maybe look into the events and make sure they are a bit more accurate, the "buttonPushed" event only triggers when a node is clicked atm, so maybe it needs to be renamed?

Have yet to manage to trigger to mouse event from an android, so they may be unecessary.

I might be completely wrong about this though, so please correct me if that is the case.
Love the chart btw, exactly what I need. :)

**Comment by hichbra** [comment]
Graphstream is originally an API designed for computers. In order to facilitate the transition between Java and Android, little has been changed from the user's point of view. It is therefore possible that there may still be inconsistencies. Graphstream being an open project, we are also counting on contributions to still improve our libraries.
